name: gpu-support
channels:
  - simpleitk
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - blosc=1.21.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.07.19
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.15.1
  - cfitsio=3.470
  - cftime=1.5.1.1
  - charls=2.2.0
  - cloudpickle=2.0.0
  - colorcet=3.0.0
  - commonmark=0.9.1
  - cryptography=37.0.1
  - curl=7.85.0
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2021.10.0
  - dataclasses=0.8
  - dbus=1.13.18
  - emcee=3.1.2
  - expat=2.4.9
  - ffmpeg=4.0
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freeglut=3.0.0
  - freetype=2.12.1
  - fsspec=2022.7.1
  - future=0.18.2
  - giflib=5.2.1
  - glib=2.69.1
  - graphite2=1.3.14
  - gst-plugins-base=1.14.0
  - gstools=1.3.5
  - gstreamer=1.14.0
  - h5py=2.8.0
  - hankel=1.2.1
  - harfbuzz=1.8.8
  - hdf4=4.2.13
  - hdf5=1.10.2
  - icu=58.2
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.19.3
  - importlib_metadata=4.11.3
  - intel-openmp=2021.4.0
  - jasper=2.0.14
  - joblib=1.1.1
  - jpeg=9e
  - jxrlib=1.1
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.85.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libgomp=11.2.0
  - libnetcdf=4.6.1
  - libnghttp2=1.46.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.9.14
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - meshio=5.3.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - ncurses=6.3
  - netcdf4=1.4.2
  - networkx=2.6.3
  - nibabel=4.0.2
  - numexpr=2.8.3
  - numpy-base=1.21.5
  - opencv=3.4.2
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.3.5
  - param=1.12.0
  - partd=1.2.0
  - patsy=0.5.2
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - py-opencv=3.4.2
  - pycparser=2.21
  - pyct=0.4.8
  - pydicom=2.3.0
  - pyevtk=1.5.0
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.7.13
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.13.0
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pywavelets=1.3.0
  - pyyaml=6.0
  - qt=5.9.7
  - readline=8.2
  - requests=2.28.1
  - rich=12.5.1
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scikit-posthocs=0.7.0
  - scipy=1.6.2
  - seaborn=0.12.0
  - setuptools=65.5.0
  - simpleitk=2.1.1.1
  - sip=4.19.8
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.39.3
  - statsmodels=0.13.2
  - tbb=2021.6.0
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tk=8.6.12
  - toolz=0.11.2
  - tornado=6.2
  - typing_extensions=4.3.0
  - urllib3=1.26.11
  - wheel=0.37.1
  - xz=5.2.6
  - yaml=0.2.5
  - zfp=0.5.5
  - zipp=3.8.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - astunparse==1.6.3
    - attrs==22.1.0
    - bm3d==3.0.9
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - comet-ml==3.31.10
    - configobj==5.0.6
    - dulwich==0.20.45
    - everett==3.0.0
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==2.11.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.34.1
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - jsonschema==4.14.0
    - keras-nightly==2.5.0.dev2021032900
    - markdown==3.4.1
    - markupsafe==2.1.1
    - numpy==1.21.6
    - pkgutil-resolve-name==1.3.10
    - protobuf==3.19.4
    - pyasn1-modules==0.2.8
    - pyrsistent==0.18.1
    - requests-oauthlib==1.3.1
    - requests-toolbelt==0.9.1
    - rsa==4.9
    - semantic-version==2.10.0
    - sentry-sdk==1.9.5
    - sewar==0.4.5
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorflow-estimator==2.5.0
    - tensorflow-gpu==2.5.0
    - termcolor==1.1.0
    - websocket-client==1.3.3
    - werkzeug==2.2.2
    - wrapt==1.12.1
    - wurlitzer==3.0.2